import Checkout from "./application/Checkout";
import GetOrdersByCpf from "./application/GetOrdersByCpf";
import Preview from "./application/Preview";
import Coupon from "./domain/entity/Coupon";
import Item from "./domain/entity/Item";
import OrderController from "./infra/controller/OrderController";
import RepositoryMemoryFactory from "./infra/factory/RepositoryMemoryFactory";
import ExpressAdapter from "./infra/http/ExpressAdapter";
import CouponRepositoryMemory from "./infra/repository/memory/CouponRepositoryMemory";
import ItemRepositoryMemory from "./infra/repository/memory/ItemRepositoryMemory";
import OrderRepositoryMemory from "./infra/repository/memory/OrderRepositoryMemory";

const itemRepository = new ItemRepositoryMemory();
itemRepository.save(new Item(1, "Guitarra", 1000));
itemRepository.save(new Item(2, "Amplificador", 5000));
itemRepository.save(new Item(3, "Cabo", 30));
const orderRepository = new OrderRepositoryMemory();
const couponRepository = new CouponRepositoryMemory();
const repositoryFactory = new RepositoryMemoryFactory();
couponRepository.save(new Coupon("VALE20", 20));
const preview = new Preview(itemRepository, couponRepository);
const checkout = new Checkout(repositoryFactory);
const getOrdersByCpf = new GetOrdersByCpf(orderRepository);
const httpServer = new ExpressAdapter();
new OrderController(httpServer, preview, checkout, getOrdersByCpf);
httpServer.listen(3000);